services:
  postgres:
    image: postgres:latest
    platform: linux/amd64
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - backend
    ports:
      - "5432:5432"
    volumes:
      - ./db_data/postgresql:/var/lib/postgresql/data
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  news-please:
    build: .
    platform: linux/amd64
    depends_on:
      - postgres
    volumes:
      - ./db_data/news_data:/root/news-please-repo/data
    networks:
      - backend
    #restart: always

networks:
  backend:
    driver: bridge


