# https://gist.github.com/palewire/12c4b2b974ef735d22da7493cf7f4d37

name: Build and Deploy to Cloud Run
on:
  push:
    paths:
      - 'news-map/**'

env:
  PROJECT_ID: news-map-ebd25
  PROJECT_NUMBER: 662353521798
  SERVICE_ACCOUNT: githubaction-news-map
  REPOSITORY: news-map-repo
  REGION_REPO: europe-west6
  REGION_SERVICE: us-central1

  ARTIFACT_NAME: news-map
  SERVICE: news-map

jobs:
  docker-release:
    name: Tagged Docker release to Google Artifact Registry
    runs-on: ubuntu-latest
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')  # <-- Notice that I'm filtering here to only run when a tagged commit is pushed

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v2

      - id: auth
        name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          token_format: access_token
          workload_identity_provider: projects/662353521798/locations/global/workloadIdentityPools/pool-news-map/providers/provider-news-map
          service_account: ${{env.SERVICE_ACCOUNT}}@${{env.PROJECT_ID}}.iam.gserviceaccount.com
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: ${{env.REGION_REPO}}-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - name: Get tag
        id: get-tag
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - id: docker-push-tagged
        name: Tag Docker image and push to Google Artifact Registry
        uses: docker/build-push-action@v2
        with:
          context: ./news-map
          dockerfile: ./news-map/Dockerfile
          push: true
          tags: |
             ${{env.REGION_REPO}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.ARTIFACT_NAME}}:${{ steps.get-tag.outputs.short_ref }}
             ${{env.REGION_REPO}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.ARTIFACT_NAME}}:latest
          build-args: |
            REACT_APP_ENV=${{env.ENVIRONMENT}}
            REACT_APP_DATABASE_NAME=${{env.DATABASE_NAME}}

    # Deploy the latest image to Google Cloud Run
      - name: Deploy to Google Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{env.SERVICE}}
          region: ${{env.REGION_SERVICE}}
          image: ${{env.REGION_REPO}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.ARTIFACT_NAME}}:${{ steps.get-tag.outputs.short_ref }}
